# Generated by Django 5.2.13 on 2026-05-08 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (uz)')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomi (ru)')),
                ('category', models.CharField(choices=[('main', 'Asosiy'), ('gk', 'Goalkeeper'), ('fitness', 'Fitness'), ('specialist', 'Mutaxassislik'), ('renewal', 'Yangilash'), ('special', 'Maxsus')], max_length=30, verbose_name='Kategoriya')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Daraja')),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='Rang (HEX)')),
                ('waiting_days', models.IntegerField(default=0, verbose_name='Kutish muddati (kun)')),
                ('min_age', models.IntegerField(default=0, verbose_name='Minimal yosh')),
                ('tashkent_only', models.BooleanField(default=False, verbose_name='Faqat Toshkent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Litsenziya turi',
                'verbose_name_plural': 'Litsenziya turlari',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Litsenziya raqami')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('pdf_url', models.URLField(blank=True, null=True, verbose_name='PDF URL')),
                ('qr_code_url', models.URLField(blank=True, null=True, verbose_name='QR kod URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan sana')),
                ('revoke_reason', models.TextField(blank=True, null=True, verbose_name='Bekor qilish sababi')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Litsenziya',
                'verbose_name_plural': 'Litsenziyalar',
                'ordering': ['-issued_at'],
            },
        ),
    ]
