# Generated by Django 5.2.13 on 2026-05-13 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_application_status'),
        ('licenses', '0002_initial'),
        ('users', '0006_auto_20260513_1848'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AddField(
            model_name='license',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.region', verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('expired', "Muddati o'tgan"), ('suspended', "To'xtatilgan"), ('revoked', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='license',
            name='suspend_reason',
            field=models.TextField(blank=True, null=True, verbose_name="To'xtatish sababi"),
        ),
        migrations.AddField(
            model_name='license',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'xtatilgan sana"),
        ),
        migrations.AddField(
            model_name='license',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='license',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license', to='applications.application', verbose_name='Ariza'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licenses.licensetype', verbose_name='Litsenziya turi'),
        ),
        migrations.AlterField(
            model_name='license',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
