# Generated by Django 5.2.13 on 2026-05-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_license_created_at_license_region_license_status_and_more'),
        ('users', '0008_alter_region_options_alter_region_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.region', verbose_name='Hudud'),
        ),
    ]
