# Generated by Django 5.2.13 on 2026-07-13 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_alter_license_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Berilgan sana'),
        ),
    ]
