# Generated by Django 5.2.13 on 2026-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_alter_license_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='Litsenziya rasmi/PDF'),
        ),
    ]
