# Generated by Django 5.2.13 on 2026-05-13 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='UFF Football System', max_length=200)),
                ('admin_email', models.EmailField(default='admin@uff.uz', max_length=254)),
                ('admin_phone', models.CharField(default='+998 71 123 45 67', max_length=30)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=50)),
                ('description', models.TextField(default="O'zbekiston Futbol Federatsiyasi - Murabbiylar litsenziyalash tizimi")),
                ('require_2fa', models.BooleanField(default=False)),
                ('strong_password_required', models.BooleanField(default=True)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('backup_schedule', models.CharField(choices=[('daily', 'Har kuni'), ('weekly', 'Haftada bir marta'), ('monthly', 'Oyda bir marta'), ('disabled', "O'chirilgan")], default='daily', max_length=20)),
                ('log_retention', models.CharField(choices=[('30', '30 kun'), ('90', '90 kun'), ('365', '1 yil'), ('forever', 'Cheksiz')], default='90', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_application', 'Yangi ariza kelganda'), ('license_expiring', 'Litsenziya muddati tugashida'), ('system_updates', 'Tizim yangilanishlari'), ('security_alerts', 'Xavfsizlik ogohlantirishlari'), ('monthly_reports', 'Oylik hisobotlar')], max_length=40)),
                ('email_enabled', models.BooleanField(default=True)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma sozlamasi',
                'verbose_name_plural': 'Bildirishnoma sozlamalari',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
