# Generated by Django 5.2.13 on 2026-07-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='description',
            field=models.TextField(default="O'zbekiston Futbol Assotsiatsiyasi"),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='UFA', max_length=200),
        ),
    ]
