# Generated by Django 5.2.13 on 2026-07-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_update_system_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='admin_email',
            field=models.EmailField(default='admin@ufa.uz', max_length=254),
        ),
    ]
