# Generated by Django 5.2.13 on 2026-08-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_alter_systemsettings_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login urinishi',
                'verbose_name_plural': 'Login urinishlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'created_at'], name='system_sett_phone_4e953f_idx')],
            },
        ),
    ]
