# Generated by Django 5.2.13 on 2026-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0005_add_login_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='max_backups',
            field=models.PositiveIntegerField(default=10, help_text="Saqlanadigan maksimal backup soni (eskilari avtomatik o'chiriladi)"),
        ),
    ]
