# Generated by Django 5.2.13 on 2026-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0006_add_max_backups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='phone',
            field=models.CharField(db_index=True, max_length=254),
        ),
    ]
