# Generated by Django 5.2.13 on 2026-05-08 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100, verbose_name='Harakat')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Obyekt turi')),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='Obyekt ID')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name="Eski ma'lumotlar")),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name="Yangi ma'lumotlar")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('app_received', 'Ariza qabul qilindi'), ('app_approved', 'Ariza tasdiqlandi'), ('app_rejected', 'Ariza rad etildi'), ('expiry_30', '30 kunda tugaydi'), ('expiry_14', '14 kunda tugaydi'), ('expiry_7', '7 kunda tugaydi'), ('docs_required', "Qo'shimcha hujjat kerak"), ('system', 'Tizim xabari')], max_length=30, verbose_name='Xabar turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan sana")),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
