# Generated by Django 5.2.13 on 2026-05-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_telegramwebhook_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='auth_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='auth_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('awaiting_lang', 'Awaiting language'), ('awaiting_phone', 'Awaiting phone'), ('awaiting_otp', 'Awaiting OTP')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
