# Generated by Django 5.2.13 on 2026-06-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_telegramuser_auth_phone_telegramuser_auth_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('app_received', 'Ariza qabul qilindi'), ('app_approved', 'Ariza tasdiqlandi'), ('app_rejected', 'Ariza rad etildi'), ('expiry_30', '30 kunda tugaydi'), ('expiry_14', '14 kunda tugaydi'), ('expiry_7', '7 kunda tugaydi'), ('docs_required', "Qo'shimcha hujjat kerak"), ('system', 'Tizim xabari'), ('admin_alert', 'Admin xabari')], max_length=30, verbose_name='Xabar turi'),
        ),
    ]
