# Generated by Django 5.2.13 on 2026-05-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana"),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='uz', max_length=5, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Bildirishnomalar yoqilgan'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light', max_length=10, verbose_name='Mavzu'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='TOTP secret'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA yoqilgan'),
        ),
    ]
