# Generated by Django 5.2.13 on 2026-05-13 09:05

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_deleted_at_user_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_avatar_path, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='coaching_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Murabbiylik tajribasi (yil)'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar URL (legacy)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10, null=True, verbose_name='Jins'),
        ),
    ]
