# Generated by Django 5.2.13 on 2026-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_coaching_years_user_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name="To'liq manzil"),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tuman/Shahar'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_coach',
            field=models.BooleanField(default=True, verbose_name='Faol murabbiy'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
    ]
