# Generated by Django 5.2.13 on 2026-05-13 13:48

from django.db import migrations


def set_existing_users_onboarded(apps, schema_editor):
    """Set is_onboarded=True for existing users"""
    User = apps.get_model('users', 'User')
    User.objects.filter(is_onboarded=False).update(is_onboarded=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_address_remove_user_district_and_more'),
    ]

    operations = [
        migrations.RunPython(set_existing_users_onboarded),
    ]
