# Generated by Django 5.2.13 on 2026-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20260513_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Zaxira kodlari'),
        ),
    ]
