# Generated by Django 5.2.13 on 2026-05-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_recovery_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['id'], 'verbose_name': 'Hudud', 'verbose_name_plural': 'Hududlar'},
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hudud nomi (ru)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Hudud nomi (uz)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.region', verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('coach', 'Murabbiy'), ('region_admin', 'Hudud admin'), ('super_admin', 'Super admin'), ('viewer', 'Tomoshabin')], default='coach', max_length=20, verbose_name='Rol'),
        ),
    ]
