# Generated by Django 5.2.13 on 2026-07-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_region_options_alter_region_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (kod yuborilgan)'),
        ),
    ]
