from django.urls import path
from .views import (
    ChangePasswordView,
    ChangePhoneView,
    CompleteOnboardingView,
    DeleteAccountView,
    ExportUserDataView,
    TwoFactorDisableView,
    TwoFactorSetupView,
    TwoFactorVerifyView,
    UserProfileView,
    UserAvatarView,
)

urlpatterns = [
    path('me', UserProfileView.as_view(), name='user-profile'),
    path('me/', UserProfileView.as_view()),
    path('me/avatar', UserAvatarView.as_view(), name='user-avatar'),
    path('me/avatar/', UserAvatarView.as_view()),
    path('onboarding/complete', CompleteOnboardingView.as_view(), name='onboarding-complete'),
    path('onboarding/complete/', CompleteOnboardingView.as_view()),
    path('change-phone', ChangePhoneView.as_view(), name='change-phone'),
    path('change-phone/', ChangePhoneView.as_view()),
    path('change-password', ChangePasswordView.as_view(), name='change-password'),
    path('change-password/', ChangePasswordView.as_view()),
    path('2fa/setup', TwoFactorSetupView.as_view(), name='2fa-setup'),
    path('2fa/setup/', TwoFactorSetupView.as_view()),
    path('2fa/verify', TwoFactorVerifyView.as_view(), name='2fa-verify'),
    path('2fa/verify/', TwoFactorVerifyView.as_view()),
    path('2fa/disable', TwoFactorDisableView.as_view(), name='2fa-disable'),
    path('2fa/disable/', TwoFactorDisableView.as_view()),
    path('me/export', ExportUserDataView.as_view(), name='export-data'),
    path('me/export/', ExportUserDataView.as_view()),
    path('me/delete', DeleteAccountView.as_view(), name='delete-account'),
    path('me/delete/', DeleteAccountView.as_view()),
]
