from django.urls import path
from .views import (
    ChangePasswordView,
    ChangePhoneView,
    CompleteOnboardingView,
    DeleteAccountView,
    ExportUserDataView,
    TwoFactorDisableView,
    TwoFactorSetupView,
    TwoFactorVerifyView,
    TwoFactorRecoveryCodesView,
    UserProfileView,
    UserAvatarView,
    UserDashboardView,
)
from .admin_views import (
    AdminUserStatsView,
    AdminUserListView,
    AdminUserDetailView,
    AdminUserUpdateView,
    AdminUserToggleActiveView,
    AdminUserDeleteView,
    AdminUserCreateView,
    AdminUserResetPasswordView,
    AdminRegionListView,
    AdminUserExportView,
)

urlpatterns = [
    path('me', UserProfileView.as_view(), name='user-profile'),
    path('me/', UserProfileView.as_view()),
    path('me/dashboard', UserDashboardView.as_view(), name='user-dashboard'),
    path('me/dashboard/', UserDashboardView.as_view()),
    path('me/avatar', UserAvatarView.as_view(), name='user-avatar'),
    path('me/avatar/', UserAvatarView.as_view()),
    path('onboarding/complete', CompleteOnboardingView.as_view(), name='onboarding-complete'),
    path('onboarding/complete/', CompleteOnboardingView.as_view()),
    path('change-phone', ChangePhoneView.as_view(), name='change-phone'),
    path('change-phone/', ChangePhoneView.as_view()),
    path('change-password', ChangePasswordView.as_view(), name='change-password'),
    path('change-password/', ChangePasswordView.as_view()),
    path('2fa/setup', TwoFactorSetupView.as_view(), name='2fa-setup'),
    path('2fa/setup/', TwoFactorSetupView.as_view()),
    path('2fa/verify', TwoFactorVerifyView.as_view(), name='2fa-verify'),
    path('2fa/verify/', TwoFactorVerifyView.as_view()),
    path('2fa/disable', TwoFactorDisableView.as_view(), name='2fa-disable'),
    path('2fa/disable/', TwoFactorDisableView.as_view()),
    path('2fa/recovery-codes', TwoFactorRecoveryCodesView.as_view(), name='2fa-recovery-codes'),
    path('2fa/recovery-codes/', TwoFactorRecoveryCodesView.as_view()),
    path('me/export', ExportUserDataView.as_view(), name='export-data'),
    path('me/export/', ExportUserDataView.as_view()),
    path('me/delete', DeleteAccountView.as_view(), name='delete-account'),
    path('me/delete/', DeleteAccountView.as_view()),

    # ───── Admin Users Management ─────
    path('admin/stats', AdminUserStatsView.as_view(), name='admin-users-stats'),
    path('admin/stats/', AdminUserStatsView.as_view()),
    path('admin/list', AdminUserListView.as_view(), name='admin-users-list'),
    path('admin/list/', AdminUserListView.as_view()),
    path('admin/regions', AdminRegionListView.as_view(), name='admin-regions'),
    path('admin/regions/', AdminRegionListView.as_view()),
    path('admin/create', AdminUserCreateView.as_view(), name='admin-users-create'),
    path('admin/create/', AdminUserCreateView.as_view()),
    path('admin/export', AdminUserExportView.as_view(), name='admin-users-export'),
    path('admin/export/', AdminUserExportView.as_view()),
    path('admin/<uuid:user_id>', AdminUserDetailView.as_view(), name='admin-users-detail'),
    path('admin/<uuid:user_id>/', AdminUserDetailView.as_view()),
    path('admin/<uuid:user_id>/update', AdminUserUpdateView.as_view(), name='admin-users-update'),
    path('admin/<uuid:user_id>/update/', AdminUserUpdateView.as_view()),
    path('admin/<uuid:user_id>/toggle-active', AdminUserToggleActiveView.as_view(), name='admin-users-toggle'),
    path('admin/<uuid:user_id>/toggle-active/', AdminUserToggleActiveView.as_view()),
    path('admin/<uuid:user_id>/reset-password', AdminUserResetPasswordView.as_view(), name='admin-users-reset-pw'),
    path('admin/<uuid:user_id>/reset-password/', AdminUserResetPasswordView.as_view()),
    path('admin/<uuid:user_id>/delete', AdminUserDeleteView.as_view(), name='admin-users-delete'),
    path('admin/<uuid:user_id>/delete/', AdminUserDeleteView.as_view()),
]
