# Generated by Django 5.2.13 on 2026-05-08 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('under_review', "Ko'rib chiqilmoqda"), ('additional_docs', "Qo'shimcha hujjatlar kerak"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holati')),
                ('workplace', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ish joyi')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim')),
                ('coaching_years', models.IntegerField(blank=True, null=True, verbose_name='Murabbiylik tajribasi (yil)')),
                ('prev_license_date', models.DateField(blank=True, null=True, verbose_name='Oldingi litsenziya sanasi')),
                ('license_validity_start', models.DateField(blank=True, null=True, verbose_name='Litsenziya boshlanish sanasi')),
                ('license_validity_end', models.DateField(blank=True, null=True, verbose_name='Litsenziya tugash sanasi')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Admin izohi')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rad etish sababi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Yuborildi'), ('under_review', "Ko'rib chiqilmoqda"), ('additional_docs', "Qo'shimcha hujjatlar so'raldi"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('resubmitted', 'Qayta yuborildi')], max_length=30, verbose_name='Harakat')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Ariza tarixi',
                'verbose_name_plural': 'Ariza tarixlari',
                'ordering': ['created_at'],
            },
        ),
    ]
