# Generated by Django 5.2.13 on 2026-05-08 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.licensetype', verbose_name='Litsenziya turi'),
        ),
    ]
