# Generated by Django 5.2.13 on 2026-05-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
        ('licenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='license_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licenses.licensetype', verbose_name='Litsenziya turi'),
        ),
    ]
