# Generated by Django 5.2.13 on 2026-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ism"),
        ),
    ]
