# Generated by Django 5.2.13 on 2026-05-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_application_status'),
        ('users', '0007_user_recovery_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='residence_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residence_applications', to='users.region', verbose_name='Yashaydigan hudud'),
        ),
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_applications', to='users.region', verbose_name="O'qimoqchi bo'lgan hudud"),
        ),
    ]
