# Generated by Django 5.2.13 on 2026-05-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_residence_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('under_review', "Ko'rib chiqilmoqda"), ('additional_docs', "Qo'shimcha hujjatlar kerak"), ('approved', 'Tasdiqlangan'), ('graduated', "O'qib tugatgan"), ('rejected', 'Rad etilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
