# Generated by Django 5.2.13 on 2026-05-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('under_review', "Ko'rib chiqilmoqda"), ('additional_docs', "Qo'shimcha hujjatlar kerak"), ('approved', 'Tasdiqlangan'), ('called', 'Telefon qilib chaqirilgan'), ('studying', "O'qiyotgan"), ('completed', "O'qib bitirgan"), ('rejected', 'Rad etilgan'), ('cancelled', 'Bekor qilingan'), ('no_show', 'Kelmay qoldi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
