# Generated by Django 5.2.13 on 2026-05-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_add_study_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_offline',
            field=models.BooleanField(default=False, verbose_name='Daftardan kiritilgan'),
        ),
        migrations.AddField(
            model_name='application',
            name='queue_priority',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Navbatdagi o'rinni belgilaydi. Daftardagilar uchun ro'yxatga olingan sana, platforma uchun ariza vaqti.", null=True, verbose_name='Navbat tartibi (sana)'),
        ),
    ]
