# Generated by Django 5.2.13 on 2026-05-08 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('passport', 'Pasport'), ('photo_3x4', 'Rasm 3x4'), ('prev_license', 'Oldingi litsenziya'), ('certificate', 'Sertifikat'), ('diploma', 'Diplom'), ('medical', 'Meditsina xulosasi'), ('other', 'Boshqa')], max_length=30, verbose_name='Hujjat turi')),
                ('file_url', models.TextField(verbose_name='Fayl URL')),
                ('file_name', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('file_size', models.IntegerField(verbose_name='Fayl hajmi (bayt)')),
                ('mime_type', models.CharField(max_length=50, verbose_name='MIME turi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tekshirilgan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
