# Generated by Django 5.2.13 on 2026-05-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('monthly', 'Oylik'), ('quarterly', 'Choraklik'), ('yearly', 'Yillik'), ('custom', 'Maxsus')], max_length=20, verbose_name='Hisobot turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('generating', 'Yaratilmoqda'), ('completed', 'Yakunlangan'), ('failed', 'Xatolik')], default='generating', max_length=20, verbose_name='Holati')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Fayl URL')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parametrlar')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Hisobot',
                'verbose_name_plural': 'Hisobotlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
